### PR TITLE
Add slack alerts

### PR DESCRIPTION
**Pull request by orcutt989**
I have no idea if this works since my local Pulumi cluster auth is broken for some reason.

### CODE REVIEW

**Review by nicolasochem — APPROVED** [review]
the preview looks good, at least. I see that I had already added a monitoring ts file when I recreated the cluster. So this looks good, please just make sure we are installing the most recent chart.

**Comment by harryttd** [comment]
> I have no idea if this works since my local Pulumi cluster auth is broken for some reason.

The cluster has been destroyed and re-created a few times. you might need a new kubeconfig

**Comment by orcutt989** [comment]
> > I have no idea if this works since my local Pulumi cluster auth is broken for some reason.
> 
> 
> 
> The cluster has been destroyed and re-created a few times. you might need a new kubeconfig

I have a valid kubeconfig that K9S is using so I'm not sure what Pulumi would be using.

**Comment by harryttd** [comment]
> > > I have no idea if this works since my local Pulumi cluster auth is broken for some reason.
> > 
> > 
> > The cluster has been destroyed and re-created a few times. you might need a new kubeconfig
> 
> I have a valid kubeconfig that K9S is using so I'm not sure what Pulumi would be using.

Pulumi gets the correct kconfig on its own. To use k9s we need a valid one, but if one didn't refresh the kconfig they had when the cluster was re-created it would be out of date.

**Comment by orcutt989** [comment]
> > > > I have no idea if this works since my local Pulumi cluster auth is broken for some reason.
> > > 
> > > 
> > > The cluster has been destroyed and re-created a few times. you might need a new kubeconfig
> > 
> > 
> > I have a valid kubeconfig that K9S is using so I'm not sure what Pulumi would be using.
> 
> Pulumi gets the correct kconfig on its own. To use k9s we need a valid one, but if one didn't refresh the kconfig they had when the cluster was re-created it would be out of date.

Great! So what is your suggestion? I created a new kubeconfig and it works with kubectl. I fed it in to pulumi preview and I still get the same error.

**Comment by harryttd** [comment]
hmmmm. For k9s/kubectl if the kubeconfig is working that's good. Pulumi shouldn't need to have a kubeconfig fed into it tho.

**Review by nicolasochem — APPROVED** [review]
let's see

**Pull request merged**
